# Временная конфигурация только для получения сертификата
server {
    listen 80;
    server_name dispatcher-tool.stigri.work;

    # ACME validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Все остальное перенаправить на https (когда сертификат будет)
    location / {
        return 301 https://$host$request_uri;
    }
}
